apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      lables:
        app: my-app
    spec:
      serviceAccountName: prod-deben-backend-sa
      containers:
      - name: my-app
        image: nginx:latest
