apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "prod-deben-backend-role"
        vault.hashicorp.com/agent-inject-secret-config.json: "kv/data/prod-deben-backend"
        vault.hashicorp.com/agent-inject-template-config.json: |
          {{- with secret "kv/data/prod-deben-backend" -}}
          {{- range $k, $v := .Data.data -}}
          "{{ $k }}": "{{ $v }}",
          {{- end -}}
          {{- end -}}
        vault.hashicorp.com/agent-inject-file-config.json: "application.properties.json"
    spec:
      serviceAccountName: prod-deben-backend-sa
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
